### ISSUE TITLE
broken -DSC_SYMLINK_CLASSLIB=ON

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1119]
ec564e2 breaks -DSC_SYMLINK_CLASSLIB=ON

it copies the HID yaml files directly to the SCClassLibrary in the install folder, preventing/overwriting the symlink and therefore removes classes from being seen by sclang

**Comment by bagong** [comment]
There are two issues here. I think the portable-issue has been postponed to 3.8, and there is a consensus on removing the symlink stuff.

**Comment by crucialfelix** [comment]
Actually its really annoying to not have the classlib SYMLINK option. I'm working on something using the latest build and dammit ... the class library is at

/Users/crucial/code/supercollider/build/editors/sc-ide/Debug/SuperCollider.app/Contents/Resources/SCClassLibrary

if I edit it in the IDE then its not the version that is in source control. I don't want to fool around with the LanguageConfig and exclude this Debug/ path and include the source control one. its more fragile.

**Comment by bagong** [comment]
Why?

**Comment by miguel-negrao** [comment]
> if I edit it in the IDE then its not the version that is in source control. I don't want to fool around with the LanguageConfig and exclude this Debug/ path and include the source control one. its more fragile.

I guess your problem is that you have to put the explicit path to exclude which is somewhere inside that specific bundle ? Wouldn't this be fixed if the IDE could pass the -a option to sclang ? 

I've also been thinking that to have ide standalones in 3.7 the IDE could just pass the -a flat to sclang ? I'm thinking out loud, possibly missing some other stuff that would need to be taken care of.

**Comment by crucialfelix** [comment]
because a developer should not have to go through so many fragile steps just to be able to compile and run supercollider and have the classfiles be the ones that are in source control. if its a debug build then I don't want it building as if it was doing an install (copying files).

it seems to be broken anyway, though this might be a dirty cmake problem.

```shell
cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt5` -DSC_SYMLINK_CLASSLIB=ON ..
-- SuperCollider Version: 3.7alpha0
-- Building from branch topic/quarks-gui-enhancements, commit hash is de5be6f
...
-- Will create symlink of SCClassLibrary to /usr/local/Cellar/supercollider/3.7-head/SuperCollider/SCClassLibrary
-- Will create symlink of HelpSource to /usr/local/Cellar/supercollider/3.7-head/SuperCollider/HelpSource
```

why did it just say it would symlink those to Cellar ??

**Comment by crucialfelix** [comment]
You cannot exclude that build folder using the IDE:

![screen shot 2015-03-29 at 15 13 29](https://cloud.githubusercontent.com/assets/218738/6885574/4b7d7070-d626-11e4-93ce-13a2c61edfc7.png)

and you cannot edit that entry using the IDE.  recompiling resulted in duplicate class errors. shouldn't those classes have been excluded ?

used atom to fix the sc ide config

```yaml
includePaths:
    - /Users/crucial/Library/Application Support/SuperCollider/downloaded-quarks/Hadron
    - /Users/crucial/Library/Application Support/SuperCollider/downloaded-quarks/HadronPlugins
    - /Users/crucial/code/supercollider/SCClassLibrary
excludePaths:
    - /Users/crucial/code/supercollider/build/editors/sc-ide/Debug/SuperCollider.app/Contents/Resources/SCClassLibrary
postInlineWarnings: false
```

That took me far too long. If I build with a different target or build setting then I have to reconfigure it. Anytime I wipe my settings I have to reconfigure it.
