### ISSUE TITLE
Package 3.8.0+ for Debian

### ISSUE THREAD

**Issue by nhthn** [supercollider/supercollider#2917]
probably one of the most important issues right now but i've been procrastinating on investigating it. we need thorough documentation on the exact steps for packaging and releasing SC for all platforms. through the natural cycle of people retiring from and joining the project, it seems like some of this apparently oral tradition has been lost. as a result, i am left in the dark on some steps that need to be done for release.

the most important open questions are:

- how do we package binaries for linux?
- how do we update the linux repositories?

**Comment by snappizz** [comment]
good news -- artem popov has kindly granted me administrator access to the [launchpad PPA](https://launchpad.net/~supercollider) :)

i think it's rather important that we get packages going for 3.7 and 3.8!

**Comment by patrickdupuis** [comment]
yes! 👍

**Comment by snappizz** [comment]
some links i found:

- https://help.launchpad.net/Packaging/PPA/Uploading
- http://packaging.ubuntu.com/html/
- https://help.launchpad.net/Packaging/PPA/BuildingASourcePackage
- https://wiki.debian.org/Packaging/Intro
- https://wiki.debian.org/Packaging

**Comment by edmondhowser** [comment]
I'll look at debian packaging this weekend.

**Comment by brianlheim** [comment]
@edmondhowser any news?

@snappizz - I looked at the macOS releases, and from 3.7.0 on they're just the latest-master build zips from AWS (http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/master-latest.html). i.e. the .dmg installer hasn't been released since 3.6.6. I can spend some time with the dmg packager but would you be open to releasing the .zip archive for the release?

**Comment by brianlheim** [comment]
actually, looking at `.travis.yml`, it appears that an OSX release will be uploaded automatically when a commit has been tagged:

```yaml
 # github releases - only tags
 - provider: releases
   api_key: $GITHUB_KEY
   file: $HOME/artifacts/SC-$TRAVIS_COMMIT.zip
   prerelease: true
   skip_cleanup: true
   on:
     condition: $TRAVIS_OS_NAME = osx && ! -z $GITHUB_KEY
     tags: true
     all_branches: true
```
