### ISSUE TITLE
Compiling directory defaults to GateKeeper tmp dir

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3714]
On OSX 10.13.3 (17D47) with most recent SuperCollider binary downloaded from the [releases](https://github.com/supercollider/supercollider/releases/tag/Version-3.9.3) page and installed in my Applications folder, the `compiling directory` is set to

```txt
	Compiling directory '/private/var/folders/mh/8fpgg3_n77b2vbmvtbpphjjw0000gn/T/AppTranslocation/00F8E63C-1992-4EE6-AA8B-7EE9A7A960EF/d/SuperCollider.app/Contents/Resources/SCClassLibrary'
```

What I want to do:
I want to consistently exclude the standard SCClass library and substituting it with a custom one. This used to be possible with a yaml config file like this:

```yaml
includePaths:
    -   /localvol/sound/src/supercollider/SCClassLibrary
excludePaths:
    -   Users/tboverma/Applications/SuperCollider 3.9.3/SuperCollider.app/Contents/Resources/SCClassLibrary/
postInlineWarnings: false
```

The dynamically (and temporarily) assigned path (via OSX 10.13's GateKeeper?) prevents me from determining the path of the default `SCClassLibrary`.

For the records, the duplicate Class errors are of this style:

```txt
ERROR: duplicate Class found: 'SynthControl' 
/private/var/folders/mh/8fpgg3_n77b2vbmvtbpphjjw0000gn/T/AppTranslocation/8447E47C-8BCD-4255-851E-A44326101CF1/d/SuperCollider.app/Contents/Resources/SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc
/localvol/sound/src/supercollider/SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc
```
