### ISSUE TITLE
Document categories are hidden under the menu bar

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3940]
Summary: css needs to account for different heights of the menu bar, depending on browser width.

I'm pretty sure SCDoc used to display a list of document categories at the top. And in fact, I find that the HTML renderer is producing, for example, this for ControlSpec:

```
 | <span id='categories'><a href='./../Browse.html#Control'>Control</a> | <a href='./../Browse.html#Spec'>Spec</a></span>
```

But I couldn't see this text.

It turns out, if the help browser window is relatively narrow and the menu bar wraps around to two lines, then the top line of text (the categories) is underneath the menu bar. But if I expand the help browser window to full screen width, then the menubar is one line and the categories appear.

Wide window (categories highlighted with red underline):

![wide-help-window](https://user-images.githubusercontent.com/318301/43677903-c75f7820-97d7-11e8-9846-56ab15169a92.png)

Narrow window (categories are invisible):

![narrow-help-window](https://user-images.githubusercontent.com/318301/43677907-d5e1b05c-97d7-11e8-9cdb-faaff0bce01b.png)

(Note that these images are both produced with the scrollbar at the top. It's impossible to scroll any further up.)

**Comment by prko** [comment]
I observed it when I was updating the SCDoc.css, but I forgot to mention it.

I think the line ` position: fixed;`
cause this issue in:
```css
#menubar {
    position: fixed; /* fixed; */ /* relative; */
     font-family: Arial, Helvetica, sans-serif; 
    /*text-indent: 0;*/
    width: 100%;
    padding: 0.2em 0;
    background-color: #f9f9f9;
    box-shadow: 0 0 0.25em rgba(128, 128, 128, 0.5);    
}
```
Adding `padding-top: 1.3em;` can fix it, but I am not sure if it is a good fix.
```css
.header {
  padding-top: 1.3em; // this could fix the issue.
  padding-bottom: 0.18em;
}
```
In the current SCDoc.css in online documents, the two parts of codes are as follows:
```css
#menubar {
    font-family: Arial, Helvetica, sans-serif;
    text-indent: 0;
    padding: 0;
    width: 100%;
    padding: 0.5em 0;
    border-bottom: 1px solid #ccc;
    margin-bottom: 1em;
}
```
and
```css
.header {
  padding-bottom: 0.18em;
}
```
Strangely, `margin-bottom: 1em;` does not work because of `position: fixed;`
