### ISSUE TITLE
[SCDoc] Merge conflicts got merged

### ISSUE THREAD

**Issue by gusano** [supercollider/supercollider#4094]
It seems that merge conflicts got merged within `develop` branch from `3.10` branch in `scdoc.css`:

https://github.com/supercollider/supercollider/blob/develop/HelpSource/scdoc.css#L375-L394

```css
pre {
    border-left: 2px solid #e0e0e0;
<<<<<<< HEAD
    padding-left: 0.5em;
}

||||||| merged common ancestors
    padding-left: 1em;
}

code.code, pre.code {
}

pre.code {

}

=======
    padding-left: 1em;
}

>>>>>>> 3.10
```

c35cee1 is the offending merge commit (cc @snappizz )
